// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThesisBackend.Data;

#nullable disable

namespace ThesisBackend.Migrations.TestSession
{
    [DbContext(typeof(TestSessionContext))]
    [Migration("20260218143115_TestSessionModels")]
    partial class TestSessionModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThesisBackend.Models.TestSessionModels.TestResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResultId"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<float>("ScorePercentage")
                        .HasColumnType("real");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("Skipped")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ResultId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("ThesisBackend.Models.TestSessionModels.TestSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TestTakenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SessionId");

                    b.ToTable("TestSessions");
                });

            modelBuilder.Entity("ThesisBackend.Models.TestSessionModels.TestResult", b =>
                {
                    b.OwnsMany("ThesisBackend.Models.TestSessionModels.DetailedQuestionResult", "DetailedResults", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("CorrectAnswerId")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsCorrect")
                                .HasColumnType("boolean");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<int>("QuestionId")
                                .HasColumnType("integer");

                            b1.Property<int>("ResultId")
                                .HasColumnType("integer");

                            b1.Property<int?>("SubmittedAnswerId")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("ResultId");

                            b1.ToTable("DetailedQuestionResult");

                            b1.WithOwner()
                                .HasForeignKey("ResultId");
                        });

                    b.Navigation("DetailedResults");
                });

            modelBuilder.Entity("ThesisBackend.Models.TestSessionModels.TestSession", b =>
                {
                    b.OwnsMany("ThesisBackend.Models.TestSessionModels.TestComponent", "TestComponents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("SessionId")
                                .HasColumnType("integer");

                            b1.Property<int>("answer_id")
                                .HasColumnType("integer");

                            b1.Property<int>("question_id")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.ToTable("TestComponent");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("TestComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
